/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author samsung
 */
public class CadastroPet extends javax.swing.JFrame {

  private String origem;
private int idTutor;
    
 public CadastroPet(String origem) {
    initComponents();
    this.origem = origem;
    carregarTutores();
}
  
    public CadastroPet() {
        initComponents();
        carregarTutores();
    }
    
    public CadastroPet(String origem, int idTutor) {
    initComponents();

    this.origem = origem;
    this.idTutor = idTutor;

    carregarTutores();

    for (int i = 0; i < jComboBoxTutor.getItemCount(); i++) {

        String item = jComboBoxTutor.getItemAt(i);

        int id = Integer.parseInt(
                item.split(" - ")[0]
        );

        if (id == idTutor) {
            jComboBoxTutor.setSelectedIndex(i);
            break;
        }
    }

    jComboBoxTutor.setEnabled(false);
}

    private void carregarTutores() {

    DAO.TutorDAO tutorDAO = new DAO.TutorDAO();

    for (DTO.TutorDTO tutor : tutorDAO.listar()) {

        jComboBoxTutor.addItem(
            tutor.getIdTutor() + " - " + tutor.getNome()
        );
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastrarPet = new javax.swing.JLabel();
        jLabelTutor = new javax.swing.JLabel();
        jLabelEspecie = new javax.swing.JLabel();
        jLabelPorte = new javax.swing.JLabel();
        jComboBoxTutor = new javax.swing.JComboBox<>();
        jComboBoxEspecie = new javax.swing.JComboBox<>();
        jComboBoxPorte = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCadastrarPet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCadastrarPet.setText("Cadastrar Pet");

        jLabelTutor.setText("Tutor:");

        jLabelEspecie.setText("Especie:");

        jLabelPorte.setText("Porte:");

        jComboBoxTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTutorActionPerformed(evt);
            }
        });

        jComboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato", "Outro" }));

        jComboBoxPorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Médio", "Grande" }));
        jComboBoxPorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPorteActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar a Tela Principal");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabelCadastrarPet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPorte)
                                    .addComponent(jLabelEspecie)
                                    .addComponent(jLabelTutor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelCadastrarPet)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTutor)
                    .addComponent(jComboBoxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspecie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorte)
                    .addComponent(jComboBoxPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonVoltar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTutorActionPerformed

    private void jComboBoxPorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPorteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String nome = jTextFieldNome.getText().trim();
String especie = jComboBoxEspecie.getSelectedItem().toString();
String porte = jComboBoxPorte.getSelectedItem().toString();

if (nome.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Informe o nome do pet!"
    );

    return;
}

if (jComboBoxTutor.getSelectedItem() == null) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Selecione um tutor!"
    );

    return;
}

String tutorSelecionado =
        jComboBoxTutor.getSelectedItem().toString();

int idTutor = Integer.parseInt(
        tutorSelecionado.split(" - ")[0]
);

DTO.PetDTO pet = new DTO.PetDTO();

pet.setTutorId(idTutor);
pet.setNome(nome);
pet.setEspecie(especie);
pet.setPorte(porte);

DAO.PetDAO petDAO = new DAO.PetDAO();

petDAO.cadastrar(pet);

javax.swing.JOptionPane.showMessageDialog(
        this,
        "Pet cadastrado com sucesso!"
);

jTextFieldNome.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       
   if ("tutor".equals(origem)) {

    TelaPrincipalTutor tela =
            new TelaPrincipalTutor(idTutor);

    tela.setVisible(true);

} else {

    TelaPrincipalAtendente tela =
            new TelaPrincipalAtendente();

    tela.setVisible(true);
}

this.dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxEspecie;
    private javax.swing.JComboBox<String> jComboBoxPorte;
    private javax.swing.JComboBox<String> jComboBoxTutor;
    private javax.swing.JLabel jLabelCadastrarPet;
    private javax.swing.JLabel jLabelEspecie;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPorte;
    private javax.swing.JLabel jLabelTutor;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
