//atendente
package VIEW;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
public class AgendaDoDia extends javax.swing.JFrame {

    /**
     * Creates new form AgendaDoDia
     */
    public AgendaDoDia() {
        initComponents();
        
         carregarDatas();
    carregarAgendamentos();
    }

    
    private ArrayList<Integer> idsAgendamentos = new ArrayList<>();
    
    private void carregarDatas() {

    jComboBoxDatas.removeAllItems();

    DAO.AgendamentoDAO agendamentoDAO =
            new DAO.AgendamentoDAO();

    ArrayList<DTO.AgendamentoDTO> lista =
            agendamentoDAO.listar();

    ArrayList<String> datas =
            new ArrayList<>();

    for (DTO.AgendamentoDTO agendamento : lista) {

        String data = agendamento.getData();

        if (!datas.contains(data)) {
            datas.add(data);
        }
    }

    Collections.sort(datas);

    for (String data : datas) {
        jComboBoxDatas.addItem(data);
    }
}
    
    private void carregarAgendamentos() {

    idsAgendamentos.clear();

    DefaultListModel<String> modelo =
            new DefaultListModel<>();

    jListAgendamentos.setModel(modelo);

    if (jComboBoxDatas.getSelectedItem() == null) {
        return;
    }

    String dataSelecionada =
            jComboBoxDatas.getSelectedItem().toString();

    DAO.AgendamentoDAO agendamentoDAO =
            new DAO.AgendamentoDAO();

    ArrayList<DTO.AgendamentoDTO> lista =
            agendamentoDAO.listar();

    DAO.TutorDAO tutorDAO =
            new DAO.TutorDAO();

    DAO.PetDAO petDAO =
            new DAO.PetDAO();

    DAO.ServicoDAO servicoDAO =
            new DAO.ServicoDAO();

    DAO.FuncionarioDAO funcionarioDAO =
            new DAO.FuncionarioDAO();

    for (DTO.AgendamentoDTO agendamento : lista) {

        if (!agendamento.getData().equals(dataSelecionada)) {
            continue;
        }

        DTO.TutorDTO tutor =
                tutorDAO.buscarPorId(
                        agendamento.getTutorId()
                );

        DTO.PetDTO pet =
                petDAO.buscarPorId(
                        agendamento.getPetId()
                );

        DTO.ServicoDTO servico =
                servicoDAO.buscarPorId(
                        agendamento.getServicoId()
                );

        DTO.FuncionarioDTO funcionario =
                funcionarioDAO.buscarPorId(
                        agendamento.getFuncionarioId()
                );

        String linha =
                agendamento.getHora()
                + " - "
                + tutor.getNome()
                + " - "
                + pet.getNome()
                + " - "
                + servico.getNome()
                + " - "
                + funcionario.getNome();

        modelo.addElement(linha);

        idsAgendamentos.add(
                agendamento.getIdAgendamento()
        );
    }

    jListAgendamentos.setModel(modelo);
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldData = new javax.swing.JTextField();
        jLabelAgendaDoDia = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelExplicacao = new javax.swing.JLabel();
        jComboBoxDatas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAgendamentos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAgendaDoDia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelAgendaDoDia.setText("Agenda do Dia");

        jLabelData.setText("Data:");

        jLabelExplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelExplicacao.setText("Mostra a agenda do dia. ");

        jComboBoxDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDatasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListAgendamentos);

        jLabel1.setText("Agenda do dia:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar a Tela Principal");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelExplicacao)
                    .addComponent(jLabelAgendaDoDia))
                .addGap(24, 136, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDatas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAgendaDoDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelExplicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelData)
                            .addComponent(jComboBoxDatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void jComboBoxDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDatasActionPerformed
        carregarAgendamentos();
    }//GEN-LAST:event_jComboBoxDatasActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int indice =
        jListAgendamentos.getSelectedIndex();

if (indice == -1) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Selecione um agendamento!"
    );

    return;
}

int idAgendamento =
        idsAgendamentos.get(indice);

int resposta =
        javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente cancelar este agendamento?",
                "Cancelar agendamento",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

if (resposta != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

DAO.AgendamentoDAO agendamentoDAO =
        new DAO.AgendamentoDAO();

agendamentoDAO.excluir(idAgendamento);

javax.swing.JOptionPane.showMessageDialog(
        this,
        "Agendamento cancelado com sucesso!"
);

carregarDatas();
carregarAgendamentos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       TelaPrincipalAtendente tela = new TelaPrincipalAtendente();
tela.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaDoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaDoDia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxDatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgendaDoDia;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelExplicacao;
    private javax.swing.JList<String> jListAgendamentos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldData;
    // End of variables declaration//GEN-END:variables
}
