/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

public class AgendamentoServico extends javax.swing.JFrame {

    private String origem;
    private int idTutor;
    
    public AgendamentoServico() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        carregarTutores();
        carregarServicos();
        carregarFuncionarios();
        
    }
    
    public AgendamentoServico(String origem) {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    this.origem = origem;
    carregarTutores();
    carregarServicos();
    carregarFuncionarios();
}

   public AgendamentoServico(String origem, int idTutor) {

    initComponents();

    setDefaultCloseOperation(
            javax.swing.WindowConstants.DISPOSE_ON_CLOSE
    );

    this.origem = origem;
    this.idTutor = idTutor;

    carregarTutores();
    carregarServicos();
    carregarFuncionarios();

    // Seleciona automaticamente o tutor logado
    for (int i = 0; i < jComboBoxTutor.getItemCount(); i++) {

        String item = jComboBoxTutor.getItemAt(i);

        int id = Integer.parseInt(
                item.split(" - ")[0]
        );

        if (id == idTutor) {

            jComboBoxTutor.setSelectedIndex(i);

            break;
        }
    }

    // tutor não pode alterar o próprio tutor
    jComboBoxTutor.setEnabled(false);

    // Carrega os pets desse tutor
    carregarPetsDoTutor();
}
    
    
    private void carregarTutores() {

    DAO.TutorDAO tutorDAO = new DAO.TutorDAO();

    for (DTO.TutorDTO tutor : tutorDAO.listar()) {

        jComboBoxTutor.addItem(
            tutor.getIdTutor() + " - " + tutor.getNome()
        );
    }
}
    
    
   private void carregarPetsDoTutor() {

    jComboBoxPet.removeAllItems();

    if (jComboBoxTutor.getSelectedItem() == null) {
        return;
    }

    String tutorSelecionado =
            jComboBoxTutor.getSelectedItem().toString();

    int idTutor = Integer.parseInt(
            tutorSelecionado.split(" - ")[0]
    );

    DAO.PetDAO petDAO = new DAO.PetDAO();

    for (DTO.PetDTO pet : petDAO.listarPorTutor(idTutor)) {

        jComboBoxPet.addItem(
            pet.getIdPet() + " - " + pet.getNome()
        );
    }
}
    
   private void carregarServicos() {

    jComboBoxServico.removeAllItems();

    DAO.ServicoDAO servicoDAO = new DAO.ServicoDAO();

    for (DTO.ServicoDTO servico : servicoDAO.listar()) {

        if (servico.isAtivo()) {

            jComboBoxServico.addItem(
                servico.getIdServico()
                + " - "
                + servico.getNome()
                + " - R$ "
                + String.format("%.2f", servico.getPreco())
            );
        }
    }
} 
   
   private void carregarFuncionarios() {

    jComboBoxFuncionario.removeAllItems();

    DAO.FuncionarioDAO funcionarioDAO = new DAO.FuncionarioDAO();

    for (DTO.FuncionarioDTO funcionario : funcionarioDAO.listar()) {

        jComboBoxFuncionario.addItem(
            funcionario.getIdFuncionario()
            + " - "
            + funcionario.getNome()
        );
    }
}
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabelAgendamentoDeServicos = new javax.swing.JLabel();
        jLabelTutor = new javax.swing.JLabel();
        jLabelPet = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jComboBoxTutor = new javax.swing.JComboBox<>();
        jComboBoxPet = new javax.swing.JComboBox<>();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jLabelData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jButtonAgendar = new javax.swing.JButton();
        jLabelFuncionario = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAgendamentoDeServicos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelAgendamentoDeServicos.setText("Agendamento de Serviços:");

        jLabelTutor.setText("Tutor:");

        jLabelPet.setText("Pet:");

        jLabelServico.setText("Serviço:");

        jComboBoxTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTutorActionPerformed(evt);
            }
        });

        jLabelData.setText("Data:");

        jLabel5.setText("Hora:");

        jTextFieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraActionPerformed(evt);
            }
        });

        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });

        jLabelFuncionario.setText("Funcionario:");

        jButton1.setText("Voltar a Tela Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabelAgendamentoDeServicos)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTutor)
                            .addComponent(jLabelServico)
                            .addComponent(jComboBoxTutor, 0, 160, Short.MAX_VALUE)
                            .addComponent(jComboBoxServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelData)
                            .addComponent(jTextFieldData))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addComponent(jComboBoxPet, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFuncionario)
                                            .addComponent(jLabelPet))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldHora))
                                .addGap(46, 46, 46))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgendar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelAgendamentoDeServicos)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTutor)
                    .addComponent(jLabelPet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServico)
                    .addComponent(jLabelFuncionario))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jButtonAgendar)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraActionPerformed

    private void jComboBoxTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTutorActionPerformed
       carregarPetsDoTutor();
    }//GEN-LAST:event_jComboBoxTutorActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        
    
  if (jComboBoxTutor.getSelectedItem() == null
        || jComboBoxPet.getSelectedItem() == null
        || jComboBoxServico.getSelectedItem() == null
        || jComboBoxFuncionario.getSelectedItem() == null) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Selecione tutor, pet, serviço e funcionário!"
    );

    return;
}

String data = jTextFieldData.getText().trim();
String hora = jTextFieldHora.getText().trim();

if (data.isEmpty() || hora.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Informe a data e a hora!"
    );

    return;
}


DateTimeFormatter formatoData =
        DateTimeFormatter.ofPattern("dd/MM/yyyy");

LocalDate dataAgendamento;

try {

    dataAgendamento =
            LocalDate.parse(data, formatoData);

} catch (DateTimeParseException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Data inválida! Use o formato DD/MM/AAAA."
    );

    return;
}


DateTimeFormatter formatoHora =
        DateTimeFormatter.ofPattern("HH:mm");

LocalTime horaAgendamento;

try {

    horaAgendamento =
            LocalTime.parse(hora, formatoHora);

} catch (DateTimeParseException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Hora inválida! Use o formato HH:MM."
    );

    return;
}


/* DEFINE O TUTOR DO AGENDAMENTO */

int idTutorAgendamento;

if ("tutor".equals(origem)) {

    // Se for tutor, usa obrigatoriamente
    // o ID do tutor que fez login.
    idTutorAgendamento = this.idTutor;

} else {

    // Se for funcionário, pode escolher qualquer tutor.
    String tutorSelecionado =
            jComboBoxTutor.getSelectedItem().toString();

    idTutorAgendamento = Integer.parseInt(
            tutorSelecionado.split(" - ")[0]
    );
}


String petSelecionado =
        jComboBoxPet.getSelectedItem().toString();

int idPet = Integer.parseInt(
        petSelecionado.split(" - ")[0]
);


String servicoSelecionado =
        jComboBoxServico.getSelectedItem().toString();

int idServico = Integer.parseInt(
        servicoSelecionado.split(" - ")[0]
);


String funcionarioSelecionado =
        jComboBoxFuncionario.getSelectedItem().toString();

int idFuncionario = Integer.parseInt(
        funcionarioSelecionado.split(" - ")[0]
);


DAO.AgendamentoDAO agendamentoDAO =
        new DAO.AgendamentoDAO();

if (agendamentoDAO.horarioOcupado(data, hora)) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Esse horário já está ocupado!"
    );

    return;
}


DTO.AgendamentoDTO agendamento =
        new DTO.AgendamentoDTO();

agendamento.setTutorId(idTutorAgendamento);
agendamento.setPetId(idPet);
agendamento.setServicoId(idServico);
agendamento.setFuncionarioId(idFuncionario);
agendamento.setData(data);
agendamento.setHora(hora);
agendamento.setStatus("CONFIRMADO");


// salvar

agendamentoDAO.cadastrar(agendamento);

javax.swing.JOptionPane.showMessageDialog(
        this,
        "Agendamento realizado com sucesso!"
);


jTextFieldData.setText("");
jTextFieldHora.setText("");
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if ("tutor".equals(origem)) {

    TelaPrincipalTutor tela =
            new TelaPrincipalTutor(idTutor);

    tela.setVisible(true);

} else if ("atendente".equals(origem)) {

    TelaPrincipalAtendente tela =
            new TelaPrincipalAtendente();

    tela.setVisible(true);
}

this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxPet;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JComboBox<String> jComboBoxTutor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAgendamentoDeServicos;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelPet;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelTutor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHora;
    // End of variables declaration//GEN-END:variables
}
