/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
public class MeusAgendamentos extends javax.swing.JFrame {

    /**
     * Creates new form MeusAgendamentos
     */
    
   public MeusAgendamentos() {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
}

public MeusAgendamentos(int idTutor) {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    this.idTutor = idTutor;

    carregarAgendamentos();
}

    
    
    private int idTutor;

private ArrayList<Integer> idsAgendamentos =
        new ArrayList<>();


   


private void carregarAgendamentos() {

    idsAgendamentos.clear();

    DefaultListModel<String> modelo =
            new DefaultListModel<>();

    DAO.AgendamentoDAO agendamentoDAO =
            new DAO.AgendamentoDAO();

    ArrayList<DTO.AgendamentoDTO> lista =
            agendamentoDAO.listarPorTutor(idTutor);

    
    
    
    System.out.println("ID DO TUTOR: " + idTutor);
System.out.println("AGENDAMENTOS ENCONTRADOS: " + lista.size());



    
    DAO.PetDAO petDAO =
            new DAO.PetDAO();

    DAO.ServicoDAO servicoDAO =
            new DAO.ServicoDAO();

    for (DTO.AgendamentoDTO agendamento : lista) {

        DTO.PetDTO pet =
                petDAO.buscarPorId(
                        agendamento.getPetId()
                );

        DTO.ServicoDTO servico =
                servicoDAO.buscarPorId(
                        agendamento.getServicoId()
                );

        String linha =
                agendamento.getData()
                + " - "
                + agendamento.getHora()
                + " - "
                + pet.getNome()
                + " - "
                + servico.getNome()
                + " - "
                + agendamento.getStatus();

        modelo.addElement(linha);

        idsAgendamentos.add(
                agendamento.getIdAgendamento()
        );
    }

    jListAgendamentos.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMeusAgendamentos = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAgendamentos = new javax.swing.JList<>();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMeusAgendamentos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMeusAgendamentos.setText("Meus Agendamentos");

        jButtonCancelar.setText("Cancelar Agendamento");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListAgendamentos);

        jButtonVoltar.setText("Voltar a Tela Principal");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelMeusAgendamentos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVoltar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(jButtonCancelar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelMeusAgendamentos)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       int indice =
        jListAgendamentos.getSelectedIndex();

if (indice == -1) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Selecione um agendamento!"
    );

    return;
}

int idAgendamento =
        idsAgendamentos.get(indice);

int resposta =
        javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente cancelar este agendamento?",
                "Cancelar agendamento",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

if (resposta != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

DAO.AgendamentoDAO agendamentoDAO =
        new DAO.AgendamentoDAO();

agendamentoDAO.excluir(idAgendamento);

javax.swing.JOptionPane.showMessageDialog(
        this,
        "Agendamento cancelado com sucesso!"
);

carregarAgendamentos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       TelaPrincipalTutor tela =
        new TelaPrincipalTutor(idTutor);

tela.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeusAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeusAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeusAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeusAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeusAgendamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelMeusAgendamentos;
    private javax.swing.JList<String> jListAgendamentos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
